language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t dockerryokker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true SATORYOKA/docker-react npm run test


  # script:
  # - docker run USERNAME/docker-react npm run test -- --coverage


